# Generated by Django 4.2.1 on 2023-06-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0008_remove_productos_id_alter_productos_codigo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productos',
            order_with_respect_to='codigo',
        ),
    ]
