# Generated by Django 4.2.1 on 2023-06-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0012_alter_productos_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='productos',
            order_with_respect_to=None,
        ),
    ]
