# Generated by Django 4.2.1 on 2023-07-01 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0014_pedidos_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
