# Generated by Django 4.2.1 on 2023-07-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0017_carrito_imagen_carrito_productos_codigo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
