# Generated by Django 4.2.1 on 2023-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0009_delete_cliente_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='costo',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
