# Generated by Django 4.2.1 on 2023-06-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0011_alter_productos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='costo',
            field=models.IntegerField(),
        ),
    ]
