# Generated by Django 4.2.1 on 2023-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocteleria', '0016_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='imagen',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='imagenes/', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos_codigo',
            field=models.CharField(default='valor_predeterminado', max_length=150),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nombrep',
            field=models.CharField(max_length=150),
        ),
    ]
